baseURL = 'http://azkron.github.io'
languageCode = 'en-us'
title = 'Stuff by Hugo Barbáchano'
author = "Hugo Barbáchano"
canonifyurls = true
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Hugo Barbáchano"
  disableWebFonts = false
